name: Update Member Statistics

on:
  schedule:
    # 매주 일요일에서 월요일로 넘어가는 자정에 실행
    - cron: '0 0 * * 1'
  workflow_dispatch: # 수동 실행 가능
  push:
    branches: [ main ]
    paths: 
      - '.github/scripts/update_stats.py'
      - '.github/workflows/update-stats.yml'

concurrency:
  group: update-stats
  cancel-in-progress: true

jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install requests
        
    - name: Update member statistics
      run: |
        python .github/scripts/update_stats.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        echo "=== Git 상태 확인 ==="
        git status
        git log --oneline -5
        
        echo "=== 원격 상태 확인 ==="
        git fetch origin
        git log origin/main --oneline -5
        
        echo "=== 강제 동기화 ==="
        git reset --hard origin/main
        
        echo "=== 스크립트 다시 실행 ==="
        python .github/scripts/update_stats.py
        
        echo "=== 변경사항 확인 ==="
        git status
        git diff
        
        # 변경사항이 있는지 확인
        if git diff --quiet; then
          echo "❌ 변경사항이 없습니다."
          exit 0
        fi
        
        echo "=== 커밋 및 푸시 ==="
        git add .
        git commit -m "docs: 주간 자동 업데이트 - 멤버 및 팀 통계"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}