name: Update Member Statistics

on:
  schedule:
    # 매주 일요일에서 월요일로 넘어가는 자정에 실행
    - cron: '0 0 * * 1'
  workflow_dispatch: # 수동 실행 가능
  push:
    branches: [ main ]
    paths: 
      - '.github/scripts/update_stats.py'
      - '.github/workflows/update-stats.yml'

concurrency:
  group: update-stats
  cancel-in-progress: true

jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install requests
        
    - name: Debug - Check environment
      run: |
        echo "=== 환경변수 확인 ==="
        echo "CUSTOM_GITHUB_TOKEN이 설정되어 있는지: $([[ -n "$CUSTOM_GITHUB_TOKEN" ]] && echo "YES" || echo "NO")"
        echo "토큰 길이: ${#CUSTOM_GITHUB_TOKEN}"
        echo "현재 디렉토리: $(pwd)"
        echo "README 파일 존재: $(ls -la profile/README.md 2>/dev/null || echo '파일 없음')"
      env:
        CUSTOM_GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        
    - name: Update member statistics
      run: |
        echo "=== Python 스크립트 실행 ==="
        python .github/scripts/update_stats.py
        echo "스크립트 실행 완료 (종료 코드: $?)"
      env:
        CUSTOM_GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        
    - name: Debug - Check changes
      run: |
        echo "=== 변경사항 확인 ==="
        git status
        echo "=== README 내용 확인 ==="
        echo "현재 README 통계 섹션:"
        grep -A 10 "멤버별 성과" profile/README.md || echo "통계 섹션을 찾을 수 없음"
        echo "=== 변경된 파일들 ==="
        git diff --name-only || echo "변경사항 없음"
        if [ -n "$(git diff --name-only)" ]; then
          echo "✅ 변경사항 있음!"
          git diff profile/README.md || echo "README 변경사항 없음"
        else
          echo "❌ 변경사항 없음"
        fi
        
    - name: Commit and push changes
      run: |
        # Git 설정
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # 변경사항이 있는지 확인
        if git diff --quiet && git diff --cached --quiet; then
          echo "변경사항이 없어서 커밋하지 않습니다."
          exit 0
        fi
        
        echo "=== 변경사항 커밋 ==="
        git add profile/README.md
        git commit -m "docs: 주간 자동 업데이트 - 멤버 통계 $(date +'%Y-%m-%d %H:%M')"
        
        echo "=== 푸시 시도 ==="
        git push origin main
        
        echo "✅ README 업데이트 완료!"
      env:
        GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}