name: Update Member Statistics

on:
  schedule:
    # 매주 일요일에서 월요일로 넘어가는 자정에 실행
    - cron: '0 0 * * 1'
  workflow_dispatch: # 수동 실행 가능
  push:
    branches: [ main ]
    paths: 
      - '.github/scripts/update_stats.py'
      - '.github/workflows/update-stats.yml'

concurrency:
  group: update-stats
  cancel-in-progress: true

jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install requests
        
    - name: Update member statistics
      run: |
        echo "=== 환경변수 확인 ==="
        echo "CUSTOM_GITHUB_TOKEN이 설정되어 있는지: $([[ -n "$CUSTOM_GITHUB_TOKEN" ]] && echo "YES" || echo "NO")"
        echo "토큰 길이: ${#CUSTOM_GITHUB_TOKEN}"
        
        echo "=== Python 스크립트 실행 ==="
        python .github/scripts/update_stats.py
      env:
        CUSTOM_GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        echo "=== 초기 Git 상태 확인 ==="
        git status
        
        echo "=== 스크립트 실행 전 README 상태 ==="
        echo "README 존재 여부: $(ls -la profile/README.md 2>/dev/null || echo '파일 없음')"
        echo "README 앞부분:"
        head -10 profile/README.md 2>/dev/null || echo "README 읽기 실패"
        
        echo "=== 스크립트 실행 ==="
        python .github/scripts/update_stats.py
        echo "스크립트 실행 완료 (종료 코드: $?)"
        
        echo "=== 스크립트 실행 후 변경사항 확인 ==="
        git status
        git diff --name-only
        git diff profile/README.md || echo "README 변경사항 없음"
        
        echo "=== 변경된 파일들 확인 ==="
        if git diff --quiet; then
          echo "❌ 변경사항이 없습니다."
          echo "=== README 통계 섹션 확인 ==="
          grep -A 10 "멤버별 성과" profile/README.md || echo "통계 섹션을 찾을 수 없음"
          exit 0
        else
          echo "✅ 변경사항이 있습니다!"
          echo "변경된 파일들:"
          git diff --name-only
        fi
        
        echo "=== 커밋 및 푸시 ==="
        git add .
        git commit -m "docs: 주간 자동 업데이트 - 멤버 및 팀 통계"
        
        echo "=== 푸시 시도 ==="
        git push origin main || {
          echo "푸시 실패, 상태 확인:"
          git status
          git log --oneline -3
          exit 1
        }
        
        echo "✅ 성공적으로 업데이트 완료!"
      env:
        GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        CUSTOM_GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}